spring.application.name=threat-tracker-service
server.port=8082

spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=password

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

jpl.sbdb.url=https://ssd-api.jpl.nasa.gov/sbdb_query.api
jpl.cad.url=https://ssd-api.jpl.nasa.gov/cad.api